# Generated by Django 4.0.3 on 2024-04-02 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_topic_room_host_message_room_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
